services:
  web:
    build: .
    container_name: feetf1rst
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8080 --workers 3 --reload
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: feetf1rst_db
    restart: always
    environment:
      POSTGRES_DB: feetf1rst
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8257
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx:stable-alpine
    container_name: feetf1rst_nginx
    ports:
      - "8888:80"
      # - "443:443" # enable for SSL
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    restart: always

  celery_worker:
    build: .
    container_name: feetf1rst_celery_worker
    command: celery -A core worker -l info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    restart: always

  celery_beat:
    build: .
    container_name: feetf1rst_celery_beat
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    restart: always

  redis:
    image: redis:latest
    container_name: feetf1rst_redis
    ports:
      - "6380:6379"
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
